// Test generated by RoostGPT for test RoostTest using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.samples.petclinic.model.Person;

import static org.junit.jupiter.api.Assertions.*;

class Owner_getCity_fc0393fa80_Test {

    private Person person;

    @BeforeEach
    void setUp() {
        person = new Person();
    }

    @Test
    void testGetCity_WhenCityIsSet() {
        String expectedCity = "New York";
        person.setCity(expectedCity);
        String actualCity = person.getCity();
        assertEquals(expectedCity, actualCity, "Expected city to be New York but was " + actualCity);
    }

    @Test
    void testGetCity_WhenCityIsNotSet() {
        String city = person.getCity();
        assertNull(city, "Expected city to be null as it is not set yet.");
    }
}
