// Test generated by RoostGPT for test RoostTest using AI Type Open AI and AI Model gpt-4
package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.samples.petclinic.model.Person;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

public class Owner_setAddress_b094dc9d7e_Test {

    private Person person;

    @BeforeEach
    public void setup() {
        person = new Person();
    }

    @Test
    public void testSetAddress() {
        String address = "123 Main St";
        person.setAddress(address);
        assertEquals(address, person.getAddress());
    }

    @Test
    public void testSetAddress_Null() {
        String address = null;
        assertThrows(NullPointerException.class, () -> person.setAddress(address));
    }

    @Test
    public void testSetAddress_Empty() {
        String address = "";
        person.setAddress(address);
        assertEquals(address, person.getAddress());
    }
}
