// Test generated by RoostGPT for test RoostTest using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.samples.petclinic.model.Person;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Owner2_getTelephone_d5dc76821d_Test {

    private Person person;

    @BeforeEach
    void setUp() {
        person = new Person();
    }

    @Test
    public void testGetTelephone() {
        String expectedTelephone = "1234567890";
        person.setTelephone(expectedTelephone);

        String actualTelephone = person.getTelephone();
        assertEquals(expectedTelephone, actualTelephone, "Telephone should match the set value");
    }

    @Test
    public void testGetTelephoneWhenNotSet() {
        String actualTelephone = person.getTelephone();
        assertEquals(null, actualTelephone, "Telephone should be null when not set");
    }
}
