// Test generated by RoostGPT for test RoostTest using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.samples.petclinic.model.Owner;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.mockito.Mockito.when;

@ExtendWith(MockitoExtension.class)
@SpringBootTest
public class Owner_getTelephone_d5dc76821d_Test {

    @InjectMocks
    private Owner owner;

    @Mock
    private Owner mockOwner;

    @BeforeEach
    public void setUp() {
        when(mockOwner.getTelephone()).thenReturn("1234567890");
    }

    @Test
    public void testGetTelephone_success() {
        owner.setTelephone("1234567890");
        String telephone = owner.getTelephone();
        assertEquals("1234567890", telephone, "Telephone should match");
    }

    @Test
    public void testGetTelephone_fail() {
        owner.setTelephone("0987654321");
        String telephone = owner.getTelephone();
        assertEquals(mockOwner.getTelephone(), telephone, "Telephone should not match");
    }
}
