// Test generated by RoostGPT for test RoostTest using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.owner;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mock;
import org.mockito.MockitoAnnotations;
import org.springframework.samples.petclinic.visit.Visit;

import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.*;

public class Pet_addVisit_99c71f5c31_Test {

    @Mock
    private Pet pet;

    @BeforeEach
    public void setup() {
        MockitoAnnotations.initMocks(this);
    }

    @Test
    public void testAddVisitSuccess() {
        Visit visit = new Visit();
        pet.addVisit(visit);

        verify(pet, times(1)).addVisit(visit);
        assertTrue(pet.getVisits().contains(visit));
    }

    @Test
    public void testAddVisitFailure() {
        Visit visit = null;
        pet.addVisit(visit);

        verify(pet, times(1)).addVisit(visit);
        assertTrue(pet.getVisits().isEmpty());
    }
}
