// Test generated by RoostGPT for test RoostTest using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.system;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeEach;
import org.mockito.Mockito;
import org.springframework.boot.autoconfigure.cache.JCacheManagerCustomizer;
import javax.cache.CacheManager;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

class CacheConfiguration_petclinicCacheConfigurationCustomizer_65b50e9596_Test {
    
    private CacheConfiguration cacheConfiguration;
    private CacheManager cacheManager;

    @BeforeEach
    void setUp() {
        cacheConfiguration = new CacheConfiguration();
        cacheManager = Mockito.mock(CacheManager.class);
    }

    @Test
    void testPetclinicCacheConfigurationCustomizer_success() {
        JCacheManagerCustomizer customizer = cacheConfiguration.petclinicCacheConfigurationCustomizer();
        customizer.customize(cacheManager);
        verify(cacheManager, times(1)).createCache("vets", cacheConfiguration.cacheConfiguration());
    }

    @Test
    void testPetclinicCacheConfigurationCustomizer_failure() {
        JCacheManagerCustomizer customizer = cacheConfiguration.petclinicCacheConfigurationCustomizer();
        doThrow(new RuntimeException()).when(cacheManager).createCache(anyString(), any());
        assertThrows(RuntimeException.class, () -> customizer.customize(cacheManager));
    }
}
