// Test generated by RoostGPT for test aa using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class BaseEntity_isNew_70b8047511_Test {

    private BaseEntity baseEntity;

    @BeforeEach
    void setUp() {
        baseEntity = new BaseEntity();
    }

    @Test
    void testIsNew_withNullId() {
        baseEntity.setId(null); 
        assertTrue(baseEntity.isNew());
    }

    @Test
    void testIsNew_withNonNullId() {
        baseEntity.setId(1);
        assertFalse(baseEntity.isNew());
    }
}
