// Test generated by RoostGPT for test aa using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.mockito.Mockito.when;

@SpringBootTest
public class BaseEntity_getId_09ace845cd_Test {

    @MockBean
    private BaseEntity baseEntity;

    @BeforeEach
    public void setUp() {
        when(baseEntity.getId()).thenReturn(1);
    }

    @Test
    public void testGetIdSuccess() {
        Integer expectedId = 1;
        Integer actualId = baseEntity.getId();
        assertEquals(expectedId, actualId, "The expected ID does not match the actual ID.");
    }

    @Test
    public void testGetIdFailure() {
        Integer unexpectedId = 2;
        Integer actualId = baseEntity.getId();
        assertNotEquals(unexpectedId, actualId, "The unexpected ID should not match the actual ID.");
    }
}
