// Test generated by RoostGPT for test RoostTest using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class BaseEntity_getTest_cb622c11b2_Test {

    private BaseEntity baseEntity;

    @BeforeEach
    public void setUp() {
        this.baseEntity = new BaseEntity();
    }

    @Test
    public void testGetTest_WhenTestIsNull() {
        this.baseEntity.setTest(null);
        String result = this.baseEntity.getTest();
        assertEquals(null, result, "Expected null but found " + result);
    }

    @Test
    public void testGetTest_WhenTestIsNotNull() {
        String expectedTest = "Test String";
        this.baseEntity.setTest(expectedTest);
        String result = this.baseEntity.getTest();
        assertEquals(expectedTest, result, "Expected " + expectedTest + " but found " + result);
    }
}
