// Test generated by RoostGPT for test RoostTest using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class NamedEntity_toString_ceffa8036e_Test {

    private NamedEntity namedEntity;

    @BeforeEach
    public void setup() {
        this.namedEntity = new NamedEntity();
    }

    @Test
    public void testToString_withValidName() {
        String name = "Test Name";
        this.namedEntity.setName(name);
        assertEquals(name, this.namedEntity.toString(), "Expected and actual name should match");
    }

    @Test
    public void testToString_withNullName() {
        this.namedEntity.setName(null);
        assertEquals(null, this.namedEntity.toString(), "Expected and actual name should match");
    }
}
