// Test generated by RoostGPT for test aa using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;
import static org.junit.jupiter.api.Assertions.assertEquals;

@ExtendWith(MockitoExtension.class)
public class NamedEntity_toString_2393b88875_Test {

    private NamedEntity namedEntity;

    @BeforeEach
    public void setup() {
        namedEntity = new NamedEntity();
    }

    @Test
    public void testToString_withValidName() {
        // TODO: Replace "ValidName" with the actual name you want to test
        namedEntity.setName("ValidName");
        String result = namedEntity.toString();
        assertEquals("ValidName", result, "Expected and actual name should match");
    }

    @Test
    public void testToString_withEmptyName() {
        namedEntity.setName("");
        String result = namedEntity.toString();
        assertEquals("", result, "Expected and actual name should match for empty string");
    }
}
