// Test generated by RoostGPT for test aa using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class Person_getFirstName_0d799bf2a4_Test {

    private Person person;

    @BeforeEach
    public void setup() {
        person = new Person();
        person.setFirstName("John");
    }

    @Test
    public void testGetFirstNameSuccess() {
        String expectedName = "John";
        String actualName = person.getFirstName();
        assertEquals(expectedName, actualName);
    }

    @Test
    public void testGetFirstNameFailure() {
        String expectedName = "Jane";
        String actualName = person.getFirstName();
        assertEquals(expectedName, actualName);
    }
}
