// Test generated by RoostGPT for test aa using AI Type Open AI and AI Model gpt-4

package org.springframework.samples.petclinic.model;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;
import static org.junit.jupiter.api.Assertions.assertEquals;

@ExtendWith(MockitoExtension.class)
public class Person_setFirstName_f9bf7d9c2d_Test {

    private Person person;

    @BeforeEach
    public void setup() {
        person = new Person();
    }

    @Test
    public void testSetFirstName_ValidName() {
        String validName = "John";
        person.setFirstName(validName);
        assertEquals(validName, person.getFirstName(), "The first name should be set correctly");
    }

    @Test
    public void testSetFirstName_NullName() {
        person.setFirstName(null);
        assertEquals(null, person.getFirstName(), "The first name should be null");
    }
}
